services:
  nextjs:
    build: ./raspi-next-app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: raspi_db
      MYSQL_USER: raspi_user
      MYSQL_PASSWORD: raspi_pass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
